CREATE TABLE IF NOT EXISTS Cams (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    img VARCHAR(255),
    category TEXT NOT NULL,
    author INTEGER NOT NULL REFERENCES Accounts(id),
    created DATETIME NOT NULL 
);

CREATE TABLE IF NOT EXISTS Accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);