CREATE TABLE IF NOT EXISTS Cams (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    img VARCHAR(255),
    category TEXT NOT NULL,
    author INTEGER NOT NULL REFERENCES Accounts(id),
    created DATETIME NOT NULL 
);

CREATE TABLE IF NOT EXISTS Accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Comments (
    id INTEGER PRIMARY KEY,
    body TEXT NOT NULL,
    created  DATETIME NOT NULL,
    author_id INTEGER NOT NULL REFERENCES Accounts(id),
    cam_id INTEGER NOT NULL REFERENCES Cams(id)
);